name: FireflyDumper

on:
  workflow_dispatch: ~

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build FireflyDumper
      run: cd ./FireflyDumper && cargo build --release
    - name: Upload mhypbase.dll
      uses: actions/upload-artifact@v4
      with:
        name: mhypbase
        path: FireflyDumper/target/release/mhypbase.dll
